name: ab_certus
description: projeto para assinaturas digital.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #Package store local data
  shared_preferences: ^2.0.15

  #Package Animations
  lottie: ^1.3.0

  #Package Client Http
  http: ^0.13.4

  #Package read PDF
  pdfx: ^2.0.1+2

  #Package font Icons
  font_awesome_flutter: ^10.1.0

  #Package send Email
  mailer: ^5.1.0

  #Package validator form
  validatorless: ^1.2.1

  #Package picker files
  file_picker: ^4.6.0

  #Package pick file path
  path_provider: ^2.0.10

  intl: ^0.17.0

  #Package open play store and applestore
  url_launcher: ^6.1.5

  #Package using for image svg icons
  flutter_svg: ^1.1.1+1

  #Package para snackbar
  top_snackbar_flutter: ^2.1.1

  #Package mobx para controller
  mobx: ^2.0.7+5

  #Package flutter_mobx para controller
  flutter_mobx: ^2.0.6+1

  #Package modular rotas,etc
  flutter_modular: ^5.0.3
  provider: ^6.0.3
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #Package para gerar codigo
  mobx_codegen: ^2.0.7

  #Package para criar as pastas
  build_runner: ^2.2.0

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

#  assets:
  #  - assets/termos_usos_pdf/
  #  - assets/images/
  # - assets/splash/cloud1.json
  #  - assets/animations/
  #
  #  - assets/google_fonts/
  #  - lib/core/traducoes/lang/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
